### ISSUE TITLE
Show more information of the task when selecting the task

### ISSUE THREAD

**Issue by devdouglas** [gwleuverink/clickup-time-tracker#28]
Hi Guys, love your little time tracking app for click-up. 
We use a lot of templates for our projects, so most projects have the same task names. It would be great to see the workspace and folder name next to the task name in the dropdown, so it is easier to search and find the correct ticket of the project you are working on.

**Comment by gwleuverink** [comment]
Hi @devdouglas, That's great, glad you like it.

Yes we've been thinking this is an essential addition. It gets quite cumbersome if you have a large organization with lots of tasks. I have this request cooking on the backlog.

For now I'm focusing my efforts on getting the app published on the App Store. When that's done it's full steam ahead with new features and quality of life improvements 🚀 

I'll close this issue since it's more of a feature request. If you want to continue the conversation please do so in the discussions section of this repo.

Thanks!

**Comment by gwleuverink** [comment]
@devdouglas I've switched over to GH projects which uses issues under the hood. A new issue was opened requesting the same thing #30

I'll keep that one open for project management purposes
